### ISSUE TITLE
Next-scene doesn't appear

### ISSUE THREAD

**Issue by geofffox** [SimonGZ/OBS-next-scene-hotkey#2] opened 2023-08-17 09:17 UTC
Hi Simon -

I'm a meteorologist with my own studio.  I do remote weather broadcasts for stations and websites.  Like you I'm going through a deck of images/animations.

Tonight I tried to start a new scene but "next scene" didn't appear in the hotkeys.  Older versions continue to have next-scene but even duplicating one doesn't carry next-scene through.

I am using OBS 29.1.3.  Any ideas what could be wrong?

**Comment by SimonGZ** [comment] 2023-08-23 04:50
Thanks for letting me know. I was able to reproduce this problem. 

I'm not sure what's causing it, but a workaround for now is to reinstall the script after creating the new scene collection. So just remove the next-scene.lua file from the Scripts menu and then re-add it. Unfortunately you'll have to do this again if you create another new scene collection because the problem will reoccur.

I'll try to figure out what the problem is but to be honest it may be quite a while before I find the time to find a better solution.

**Comment by geofffox** [comment] 2023-08-23 06:33
Thank you, Simon.

I'm a meteorologist with my own studio doing weather forecasts for folks
around 1,000 miles from me!  It's a one-of-a-kind setup!

Geoff

**Comment by SimonGZ** [comment] 2023-10-23 22:06
[So I looked into this a little more and asked on the OBS forums about it](https://obsproject.com/forum/threads/do-scene-collections-maintain-separate-scripts-did-the-behavior-recently-change.169105/). It turns out that OBS scripts are specific to each OBS Scene Collection. So it's actually expected behavior. Now duplicating a scene collection SHOULD also duplicate the scripts, so I'm not sure why that wouldn't be working.

Apparently there is a bug where the scripts UI (the window that you use to add or delete scripts in OBS) doesn't always update properly when you switch scene collections, so that could be what's making this confusing. For now I'm closing this issue because it appears out of my control.

**Closed as completed by SimonGZ** 2023-10-23 22:06 UTC

**Comment by geofffox** [comment] 2023-10-23 23:16
Simon -  Here's how I use your extension.  Without you, I'm screwed.  This
is a raw recording.  It was edited prior to air.

Geoff
 wx -2023-10-23 15-52-01.mov
<https://drive.google.com/file/d/1JKkamOt1skf74_N25wC6fOKauxqL3FQe/view?usp=drive_web>
